### ISSUE TITLE
Strange connection

### ISSUE THREAD

**Issue by mr-miky** [ohdsp/DSP-ADAU1452#1]
I think there is something strange in the supply section.
**R307** and **R308** may not be **0 ohm** otherwise you short the **+3V3** to **GND**

**Comment by ohdsp** [comment]
Yes, correct, R308 should be not fitted.

**Comment by ohdsp** [comment]
I am close to finishing Revision 2.0 of this board which has a number of changes. One of these changes is U302 being replaced with a lower cost part which has no adjust pin for setting the voltage and so these resistor no longer exist.
